namespace LoopstationCompanionApi.Services
{
    public sealed record ParamMeta(string Label, int Min, int Max, int Default);

    public static class EffectMeta
    {
        public static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, ParamMeta>> Map
            = new Dictionary<string, IReadOnlyDictionary<string, ParamMeta>>(StringComparer.OrdinalIgnoreCase)
            {
                ["AA_LPF"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Rate", 0, 114, 0),
                    ["B"] = new("Depth", 0, 100, 50),
                    ["C"] = new("Resonance", 0, 100, 50),
                    ["D"] = new("Cutoff", 0, 100, 50),
                    ["E"] = new("Step Rate", 0, 115, 0),
                },
                ["AA_LPF_SEQ"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Sw", 0, 1, 0),
                    ["B"] = new("Sync", 0, 1, 0),
                    ["C"] = new("Retrig", 0, 1, 0),
                    ["D"] = new("Target", 0, 1, 0),
                    ["E"] = new("Seq Rate", 0, 114, 0),
                    ["F"] = new("Seq Max", 0, 15, 8),
                    ["G"] = new("Seq Val 1", 0, 100, 50),
                    ["H"] = new("Seq Val 2", 0, 100, 50),
                    ["I"] = new("Seq Val 3", 0, 100, 50),
                    ["J"] = new("Seq Val 4", 0, 100, 50),
                    ["K"] = new("Seq Val 5", 0, 100, 50),
                    ["L"] = new("Seq Val 6", 0, 100, 50),
                    ["M"] = new("Seq Val 7", 0, 100, 50),
                    ["N"] = new("Seq Val 8", 0, 100, 50),
                    ["O"] = new("Seq Val 9", 0, 100, 50),
                    ["P"] = new("Seq Val 10", 0, 100, 50),
                    ["Q"] = new("Seq Val 11", 0, 100, 50),
                    ["R"] = new("Seq Val 12", 0, 100, 50),
                    ["S"] = new("Seq Val 13", 0, 100, 50),
                    ["T"] = new("Seq Val 14", 0, 100, 50),
                    ["U"] = new("Seq Val 15", 0, 100, 50),
                    ["V"] = new("Seq Val 16", 0, 100, 50),
                },
                ["AA_BPF"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Rate", 0, 114, 0),
                    ["B"] = new("Depth", 0, 100, 50),
                    ["C"] = new("Resonance", 0, 100, 50),
                    ["D"] = new("Cutoff", 0, 100, 50),
                    ["E"] = new("Step Rate", 0, 115, 0),
                },
                ["AA_BPF_SEQ"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Sw", 0, 1, 0),
                    ["B"] = new("Sync", 0, 1, 0),
                    ["C"] = new("Retrig", 0, 1, 0),
                    ["D"] = new("Target", 0, 1, 0),
                    ["E"] = new("Seq Rate", 0, 114, 0),
                    ["F"] = new("Seq Max", 0, 15, 8),
                    ["G"] = new("Seq Val 1", 0, 100, 50),
                    ["H"] = new("Seq Val 2", 0, 100, 50),
                    ["I"] = new("Seq Val 3", 0, 100, 50),
                    ["J"] = new("Seq Val 4", 0, 100, 50),
                    ["K"] = new("Seq Val 5", 0, 100, 50),
                    ["L"] = new("Seq Val 6", 0, 100, 50),
                    ["M"] = new("Seq Val 7", 0, 100, 50),
                    ["N"] = new("Seq Val 8", 0, 100, 50),
                    ["O"] = new("Seq Val 9", 0, 100, 50),
                    ["P"] = new("Seq Val 10", 0, 100, 50),
                    ["Q"] = new("Seq Val 11", 0, 100, 50),
                    ["R"] = new("Seq Val 12", 0, 100, 50),
                    ["S"] = new("Seq Val 13", 0, 100, 50),
                    ["T"] = new("Seq Val 14", 0, 100, 50),
                    ["U"] = new("Seq Val 15", 0, 100, 50),
                    ["V"] = new("Seq Val 16", 0, 100, 50),
                },
                ["AA_HPF"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Rate", 0, 114, 0),
                    ["B"] = new("Depth", 0, 100, 50),
                    ["C"] = new("Resonance", 0, 100, 50),
                    ["D"] = new("Cutoff", 0, 100, 50),
                    ["E"] = new("Step Rate", 0, 115, 0),
                },
                ["AA_HPF_SEQ"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Sw", 0, 1, 0),
                    ["B"] = new("Sync", 0, 1, 0),
                    ["C"] = new("Retrig", 0, 1, 0),
                    ["D"] = new("Target", 0, 1, 0),
                    ["E"] = new("Seq Rate", 0, 114, 0),
                    ["F"] = new("Seq Max", 0, 15, 8),
                    ["G"] = new("Seq Val 1", 0, 100, 50),
                    ["H"] = new("Seq Val 2", 0, 100, 50),
                    ["I"] = new("Seq Val 3", 0, 100, 50),
                    ["J"] = new("Seq Val 4", 0, 100, 50),
                    ["K"] = new("Seq Val 5", 0, 100, 50),
                    ["L"] = new("Seq Val 6", 0, 100, 50),
                    ["M"] = new("Seq Val 7", 0, 100, 50),
                    ["N"] = new("Seq Val 8", 0, 100, 50),
                    ["O"] = new("Seq Val 9", 0, 100, 50),
                    ["P"] = new("Seq Val 10", 0, 100, 50),
                    ["Q"] = new("Seq Val 11", 0, 100, 50),
                    ["R"] = new("Seq Val 12", 0, 100, 50),
                    ["S"] = new("Seq Val 13", 0, 100, 50),
                    ["T"] = new("Seq Val 14", 0, 100, 50),
                    ["U"] = new("Seq Val 15", 0, 100, 50),
                    ["V"] = new("Seq Val 16", 0, 100, 50),
                },
                ["AA_PHASER"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Rate", 0, 114, 0),
                    ["B"] = new("Depth", 0, 100, 50),
                    ["C"] = new("Resonance", 0, 100, 50),
                    ["D"] = new("Manual", 0, 100, 50),
                    ["E"] = new("Step Rate", 0, 115, 0),
                    ["F"] = new("D.Level", 0, 100, 50),
                    ["G"] = new("E.Level", 0, 100, 50),
                    ["H"] = new("Stage", 0, 3, 0),
                },
                ["AA_PHASER_SEQ"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Sw", 0, 1, 0),
                    ["B"] = new("Sync", 0, 1, 0),
                    ["C"] = new("Retrig", 0, 1, 0),
                    ["D"] = new("Target", 0, 4, 2),
                    ["E"] = new("Seq Rate", 0, 114, 0),
                    ["F"] = new("Seq Max", 0, 15, 8),
                    ["G"] = new("Seq Val 1", 0, 100, 50),
                    ["H"] = new("Seq Val 2", 0, 100, 50),
                    ["I"] = new("Seq Val 3", 0, 100, 50),
                    ["J"] = new("Seq Val 4", 0, 100, 50),
                    ["K"] = new("Seq Val 5", 0, 100, 50),
                    ["L"] = new("Seq Val 6", 0, 100, 50),
                    ["M"] = new("Seq Val 7", 0, 100, 50),
                    ["N"] = new("Seq Val 8", 0, 100, 50),
                    ["O"] = new("Seq Val 9", 0, 100, 50),
                    ["P"] = new("Seq Val 10", 0, 100, 50),
                    ["Q"] = new("Seq Val 11", 0, 100, 50),
                    ["R"] = new("Seq Val 12", 0, 100, 50),
                    ["S"] = new("Seq Val 13", 0, 100, 50),
                    ["T"] = new("Seq Val 14", 0, 100, 50),
                    ["U"] = new("Seq Val 15", 0, 100, 50),
                    ["V"] = new("Seq Val 16", 0, 100, 50),
                },
                ["AA_FLANGER"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Rate", 0, 114, 0),
                    ["B"] = new("Depth", 0, 100, 50),
                    ["C"] = new("Resonance", 0, 100, 50),
                    ["D"] = new("Manual", 0, 100, 50),
                    ["E"] = new("Step Rate", 0, 115, 0),
                    ["F"] = new("D.Level", 0, 100, 50),
                    ["G"] = new("E.Level", 0, 100, 50),
                    ["H"] = new("Separation", 0, 100, 50),
                },
                ["AA_FLANGER_SEQ"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Sw", 0, 1, 0),
                    ["B"] = new("Sync", 0, 1, 0),
                    ["C"] = new("Retrig", 0, 1, 0),
                    ["D"] = new("Target", 0, 5, 2),
                    ["E"] = new("Seq Rate", 0, 114, 0),
                    ["F"] = new("Seq Max", 0, 15, 8),
                    ["G"] = new("Seq Val 1", 0, 100, 50),
                    ["H"] = new("Seq Val 2", 0, 100, 50),
                    ["I"] = new("Seq Val 3", 0, 100, 50),
                    ["J"] = new("Seq Val 4", 0, 100, 50),
                    ["K"] = new("Seq Val 5", 0, 100, 50),
                    ["L"] = new("Seq Val 6", 0, 100, 50),
                    ["M"] = new("Seq Val 7", 0, 100, 50),
                    ["N"] = new("Seq Val 8", 0, 100, 50),
                    ["O"] = new("Seq Val 9", 0, 100, 50),
                    ["P"] = new("Seq Val 10", 0, 100, 50),
                    ["Q"] = new("Seq Val 11", 0, 100, 50),
                    ["R"] = new("Seq Val 12", 0, 100, 50),
                    ["S"] = new("Seq Val 13", 0, 100, 50),
                    ["T"] = new("Seq Val 14", 0, 100, 50),
                    ["U"] = new("Seq Val 15", 0, 100, 50),
                    ["V"] = new("Seq Val 16", 0, 100, 50),
                },
                ["AA_SYNTH"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Frequency", 0, 100, 50),
                    ["B"] = new("Resonance", 0, 100, 50),
                    ["C"] = new("Decay", 0, 100, 50),
                    ["D"] = new("Balance", 0, 100, 50),
                },
                ["AA_SYNTH_SEQ"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Sw", 0, 1, 0),
                    ["B"] = new("Sync", 0, 1, 0),
                    ["C"] = new("Retrig", 0, 1, 0),
                    ["D"] = new("Target", 0, 2, 1),
                    ["E"] = new("Seq Rate", 0, 114, 0),
                    ["F"] = new("Seq Max", 0, 15, 8),
                    ["G"] = new("Seq Val 1", 0, 100, 50),
                    ["H"] = new("Seq Val 2", 0, 100, 50),
                    ["I"] = new("Seq Val 3", 0, 100, 50),
                    ["J"] = new("Seq Val 4", 0, 100, 50),
                    ["K"] = new("Seq Val 5", 0, 100, 50),
                    ["L"] = new("Seq Val 6", 0, 100, 50),
                    ["M"] = new("Seq Val 7", 0, 100, 50),
                    ["N"] = new("Seq Val 8", 0, 100, 50),
                    ["O"] = new("Seq Val 9", 0, 100, 50),
                    ["P"] = new("Seq Val 10", 0, 100, 50),
                    ["Q"] = new("Seq Val 11", 0, 100, 50),
                    ["R"] = new("Seq Val 12", 0, 100, 50),
                    ["S"] = new("Seq Val 13", 0, 100, 50),
                    ["T"] = new("Seq Val 14", 0, 100, 50),
                    ["U"] = new("Seq Val 15", 0, 100, 50),
                    ["V"] = new("Seq Val 16", 0, 100, 50),
                },
                ["AA_LOFI"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Bit Depth", 0, 31, 16),
                    ["B"] = new("Sample Rate", 0, 31, 16),
                    ["D"] = new("Balance", 0, 100, 50),
                },
                ["AA_RADIO"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("LO-FI", 0, 9, 4),
                    ["B"] = new("Level", 0, 100, 50),
                },
                ["AA_RING_MODULATOR"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Frequency", 0, 100, 50),
                    ["B"] = new("Balance", 0, 100, 50),
                    ["C"] = new("Mode", 0, 1, 0),
                },
                ["AA_RING_MODULATOR_SEQ"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Sw", 0, 1, 0),
                    ["B"] = new("Sync", 0, 1, 0),
                    ["C"] = new("Retrig", 0, 1, 0),
                    ["D"] = new("Target", 0, 0, 0),
                    ["E"] = new("Seq Rate", 0, 114, 0),
                    ["F"] = new("Seq Max", 0, 15, 8),
                    ["G"] = new("Seq Val 1", 0, 100, 50),
                    ["H"] = new("Seq Val 2", 0, 100, 50),
                    ["I"] = new("Seq Val 3", 0, 100, 50),
                    ["J"] = new("Seq Val 4", 0, 100, 50),
                    ["K"] = new("Seq Val 5", 0, 100, 50),
                    ["L"] = new("Seq Val 6", 0, 100, 50),
                    ["M"] = new("Seq Val 7", 0, 100, 50),
                    ["N"] = new("Seq Val 8", 0, 100, 50),
                    ["O"] = new("Seq Val 9", 0, 100, 50),
                    ["P"] = new("Seq Val 10", 0, 100, 50),
                    ["Q"] = new("Seq Val 11", 0, 100, 50),
                    ["R"] = new("Seq Val 12", 0, 100, 50),
                    ["S"] = new("Seq Val 13", 0, 100, 50),
                    ["T"] = new("Seq Val 14", 0, 100, 50),
                    ["U"] = new("Seq Val 15", 0, 100, 50),
                    ["V"] = new("Seq Val 16", 0, 100, 50),
                },
                ["AA_G2B"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Balance", 0, 100, 50),
                    ["B"] = new("Mode", 0, 1, 0),
                },
                ["AA_SUSTAINER"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Attack", 0, 100, 50),
                    ["B"] = new("Release", 0, 100, 50),
                    ["C"] = new("Level", 0, 100, 50),
                    ["D"] = new("Low Gain", 0, 39, 20),
                    ["E"] = new("High Gain", 0, 39, 20),
                    ["F"] = new("Sustain", 0, 100, 50),
                },
                ["AA_AUTO_RIFF"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Phrase", 0, 29, 14),
                    ["B"] = new("Tempo", 0, 114, 0),
                    ["C"] = new("Hold", 0, 1, 0),
                    ["D"] = new("Attack", 0, 100, 50),
                    ["E"] = new("Loop", 0, 1, 0),
                    ["F"] = new("Key", 0, 11, 6),
                    ["G"] = new("Balance", 0, 100, 50),
                },
                ["AA_SLOW_GEAR"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Sens", 0, 100, 50),
                    ["B"] = new("Rise Time", 0, 100, 50),
                    ["C"] = new("Level", 0, 100, 50),
                    ["D"] = new("Mode", 0, 1, 0),
                },
                ["AA_TRANSPOSE"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Trans", 0, 24, 12),
                    ["B"] = new("Mode", 0, 1, 0),
                },
                ["AA_TRANSPOSE_SEQ"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Sw", 0, 1, 0),
                    ["B"] = new("Sync", 0, 1, 0),
                    ["C"] = new("Retrig", 0, 1, 0),
                    ["D"] = new("Target", 0, 0, 0),
                    ["E"] = new("Seq Rate", 0, 114, 0),
                    ["F"] = new("Seq Max", 0, 15, 8),
                    ["G"] = new("Seq Val 1", 0, 24, 12),
                    ["H"] = new("Seq Val 2", 0, 24, 12),
                    ["I"] = new("Seq Val 3", 0, 24, 12),
                    ["J"] = new("Seq Val 4", 0, 24, 12),
                    ["K"] = new("Seq Val 5", 0, 24, 12),
                    ["L"] = new("Seq Val 6", 0, 24, 12),
                    ["M"] = new("Seq Val 7", 0, 24, 12),
                    ["N"] = new("Seq Val 8", 0, 24, 12),
                    ["O"] = new("Seq Val 9", 0, 24, 12),
                    ["P"] = new("Seq Val 10", 0, 24, 12),
                    ["Q"] = new("Seq Val 11", 0, 24, 12),
                    ["R"] = new("Seq Val 12", 0, 24, 12),
                    ["S"] = new("Seq Val 13", 0, 24, 12),
                    ["T"] = new("Seq Val 14", 0, 24, 12),
                    ["U"] = new("Seq Val 15", 0, 24, 12),
                    ["V"] = new("Seq Val 16", 0, 24, 12),
                },
                ["AA_PITCH_BEND"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Pitch", 0, 6, 3),
                    ["B"] = new("Bend", 0, 100, 50),
                    ["C"] = new("Mode", 0, 1, 0),
                },
                ["AA_PITCH_BEND_SEQ"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Sw", 0, 1, 0),
                    ["B"] = new("Sync", 0, 1, 0),
                    ["C"] = new("Retrig", 0, 1, 0),
                    ["D"] = new("Target", 0, 0, 0),
                    ["E"] = new("Seq Rate", 0, 114, 0),
                    ["F"] = new("Seq Max", 0, 15, 8),
                    ["G"] = new("Seq Val 1", 0, 100, 50),
                    ["H"] = new("Seq Val 2", 0, 100, 50),
                    ["I"] = new("Seq Val 3", 0, 100, 50),
                    ["J"] = new("Seq Val 4", 0, 100, 50),
                    ["K"] = new("Seq Val 5", 0, 100, 50),
                    ["L"] = new("Seq Val 6", 0, 100, 50),
                    ["M"] = new("Seq Val 7", 0, 100, 50),
                    ["N"] = new("Seq Val 8", 0, 100, 50),
                    ["O"] = new("Seq Val 9", 0, 100, 50),
                    ["P"] = new("Seq Val 10", 0, 100, 50),
                    ["Q"] = new("Seq Val 11", 0, 100, 50),
                    ["R"] = new("Seq Val 12", 0, 100, 50),
                    ["S"] = new("Seq Val 13", 0, 100, 50),
                    ["T"] = new("Seq Val 14", 0, 100, 50),
                    ["U"] = new("Seq Val 15", 0, 100, 50),
                    ["V"] = new("Seq Val 16", 0, 100, 50),
                },
                ["AA_ROBOT"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Note", 0, 11, 6),
                    ["B"] = new("Formant", 0, 100, 50),
                    ["C"] = new("Mode", 0, 1, 0),
                },
                ["AA_ELECTRIC"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Shift", 0, 24, 12),
                    ["B"] = new("Formant", 0, 100, 50),
                    ["C"] = new("Speed", 0, 10, 5),
                    ["D"] = new("Stability", 0, 20, 10),
                    ["E"] = new("Scale", 0, 12, 6),
                },
                ["AA_HARMONIST_MANUAL"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Voice", 0, 10, 5),
                    ["B"] = new("Formant", 0, 100, 50),
                    ["C"] = new("Pan", 0, 100, 50),
                    ["D"] = new("Key", 0, 11, 6),
                    ["E"] = new("D.Level", 0, 100, 50),
                    ["F"] = new("E.Level", 0, 100, 50),
                },
                ["AA_HARMONIST_AUTO"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Voice", 0, 6, 3),
                    ["B"] = new("Formant", 0, 100, 50),
                    ["C"] = new("Pan", 0, 100, 50),
                    ["D"] = new("Mode", 0, 1, 0),
                    ["E"] = new("Key", 0, 11, 6),
                    ["F"] = new("D.Level", 0, 100, 50),
                    ["G"] = new("E.Level", 0, 100, 50),
                },
                ["AA_VOCODER"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Carrier", 0, 10, 5),
                    ["B"] = new("Tone", 0, 100, 50),
                    ["C"] = new("Attack", 0, 100, 50),
                    ["D"] = new("Mod Sens", 0, 100, 50),
                    ["E"] = new("Carrier Thru", 0, 1, 0),
                    ["F"] = new("Balance", 0, 100, 50),
                },
                ["AA_OSC_VOCODER"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Carrier", 0, 4, 2),
                    ["B"] = new("Tone", 0, 100, 50),
                    ["C"] = new("Attack", 0, 100, 50),
                    ["D"] = new("Octave", 0, 3, 2),
                    ["E"] = new("Mod Sens", 0, 100, 50),
                    ["F"] = new("Release", 0, 100, 50),
                    ["G"] = new("Balance", 0, 100, 50),
                },
                ["AA_OSC_BOT"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("OSC", 0, 4, 2),
                    ["B"] = new("Tone", 0, 100, 50),
                    ["C"] = new("Attack", 0, 100, 50),
                    ["D"] = new("Note", 0, 103, 52),
                    ["E"] = new("Mod Sens", 0, 100, 50),
                    ["F"] = new("Balance", 0, 100, 50),
                },
                ["AA_OSC_BOT_SEQ"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Sw", 0, 1, 0),
                    ["B"] = new("Sync", 0, 1, 0),
                    ["C"] = new("Retrig", 0, 1, 0),
                    ["D"] = new("Target", 0, 0, 0),
                    ["E"] = new("Seq Rate", 0, 114, 0),
                    ["F"] = new("Seq Max", 0, 15, 8),
                    ["G"] = new("Seq Val 1", 0, 103, 52),
                    ["H"] = new("Seq Val 2", 0, 103, 52),
                    ["I"] = new("Seq Val 3", 0, 103, 52),
                    ["J"] = new("Seq Val 4", 0, 103, 52),
                    ["K"] = new("Seq Val 5", 0, 103, 52),
                    ["L"] = new("Seq Val 6", 0, 103, 52),
                    ["M"] = new("Seq Val 7", 0, 103, 52),
                    ["N"] = new("Seq Val 8", 0, 103, 52),
                    ["O"] = new("Seq Val 9", 0, 103, 52),
                    ["P"] = new("Seq Val 10", 0, 103, 52),
                    ["Q"] = new("Seq Val 11", 0, 103, 52),
                    ["R"] = new("Seq Val 12", 0, 103, 52),
                    ["S"] = new("Seq Val 13", 0, 103, 52),
                    ["T"] = new("Seq Val 14", 0, 103, 52),
                    ["U"] = new("Seq Val 15", 0, 103, 52),
                    ["V"] = new("Seq Val 16", 0, 103, 52),
                },
                ["AA_PREAMP"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Amp Type", 0, 8, 4),
                    ["B"] = new("Speaker Type", 0, 8, 4),
                    ["C"] = new("Gain", 0, 120, 60),
                    ["D"] = new("T-Comp", 0, 20, 10),
                    ["E"] = new("Bass", 0, 100, 50),
                    ["F"] = new("Middle", 0, 100, 50),
                    ["G"] = new("Treble", 0, 100, 50),
                    ["H"] = new("Presence", 0, 100, 50),
                    ["I"] = new("Mic Type", 0, 4, 2),
                    ["J"] = new("Mic Dis", 0, 1, 0),
                    ["K"] = new("Mic Pos", 0, 10, 5),
                    ["L"] = new("E.Level", 0, 100, 50),
                },
                ["AA_DIST"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Type", 0, 5, 3),
                    ["B"] = new("Tone", 0, 100, 50),
                    ["C"] = new("Dist", 0, 100, 50),
                    ["D"] = new("D.Level", 0, 100, 50),
                    ["E"] = new("E.Level", 0, 100, 50),
                },
                ["AA_DYNAMICS"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Type", 0, 18, 9),
                    ["B"] = new("Dynamics", 0, 40, 20),
                },
                ["AA_EQ"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Low Gain", 0, 40, 20),
                    ["B"] = new("Low Mid Gain", 0, 40, 20),
                    ["C"] = new("High Mid Gain", 0, 40, 20),
                    ["D"] = new("Hi Gain", 0, 40, 20),
                    ["E"] = new("Level", 0, 40, 20),
                    ["F"] = new("Low Mid Freq", 0, 27, 13),
                    ["G"] = new("Low Mid Q", 0, 5, 3),
                    ["H"] = new("High Mid Freq", 0, 40, 20),
                    ["I"] = new("High mid Q", 0, 5, 3),
                },
                ["AA_ISOLATOR"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Band", 0, 2, 1),
                    ["B"] = new("Rate", 0, 114, 0),
                    ["C"] = new("Band Level", 0, 100, 50),
                    ["D"] = new("Depth", 0, 100, 50),
                    ["E"] = new("Step Rate", 0, 115, 0),
                    ["F"] = new("Wave Form", 0, 100, 50),
                },
                ["AA_ISOLATOR_SEQ"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Sw", 0, 1, 0),
                    ["B"] = new("Sync", 0, 1, 0),
                    ["C"] = new("Retrig", 0, 1, 0),
                    ["D"] = new("Target", 0, 0, 0),
                    ["E"] = new("Seq Rate", 0, 114, 0),
                    ["F"] = new("Seq Max", 0, 15, 8),
                    ["G"] = new("Seq Val 1", 0, 100, 50),
                    ["H"] = new("Seq Val 2", 0, 100, 50),
                    ["I"] = new("Seq Val 3", 0, 100, 50),
                    ["J"] = new("Seq Val 4", 0, 100, 50),
                    ["K"] = new("Seq Val 5", 0, 100, 50),
                    ["L"] = new("Seq Val 6", 0, 100, 50),
                    ["M"] = new("Seq Val 7", 0, 100, 50),
                    ["N"] = new("Seq Val 8", 0, 100, 50),
                    ["O"] = new("Seq Val 9", 0, 100, 50),
                    ["P"] = new("Seq Val 10", 0, 100, 50),
                    ["Q"] = new("Seq Val 11", 0, 100, 50),
                    ["R"] = new("Seq Val 12", 0, 100, 50),
                    ["S"] = new("Seq Val 13", 0, 100, 50),
                    ["T"] = new("Seq Val 14", 0, 100, 50),
                    ["U"] = new("Seq Val 15", 0, 100, 50),
                    ["V"] = new("Seq Val 16", 0, 100, 50),
                },
                ["AA_OCTAVE"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Octave", 0, 2, 1),
                    ["B"] = new("Mode", 0, 1, 0),
                    ["C"] = new("Octave Level", 0, 100, 50),
                },
                ["AA_OCTAVE_SEQ"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Sw", 0, 1, 0),
                    ["B"] = new("Sync", 0, 1, 0),
                    ["C"] = new("Retrig", 0, 1, 0),
                    ["D"] = new("Target", 0, 0, 0),
                    ["E"] = new("Seq Rate", 0, 114, 0),
                    ["F"] = new("Seq Max", 0, 15, 8),
                    ["G"] = new("Seq Val 1", 0, 100, 50),
                    ["H"] = new("Seq Val 2", 0, 100, 50),
                    ["I"] = new("Seq Val 3", 0, 100, 50),
                    ["J"] = new("Seq Val 4", 0, 100, 50),
                    ["K"] = new("Seq Val 5", 0, 100, 50),
                    ["L"] = new("Seq Val 6", 0, 100, 50),
                    ["M"] = new("Seq Val 7", 0, 100, 50),
                    ["N"] = new("Seq Val 8", 0, 100, 50),
                    ["O"] = new("Seq Val 9", 0, 100, 50),
                    ["P"] = new("Seq Val 10", 0, 100, 50),
                    ["Q"] = new("Seq Val 11", 0, 100, 50),
                    ["R"] = new("Seq Val 12", 0, 100, 50),
                    ["S"] = new("Seq Val 13", 0, 100, 50),
                    ["T"] = new("Seq Val 14", 0, 100, 50),
                    ["U"] = new("Seq Val 15", 0, 100, 50),
                    ["V"] = new("Seq Val 16", 0, 100, 50),
                },
                ["AA_AUTO_PAN"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Rate", 0, 114, 0),
                    ["B"] = new("Wave Form", 0, 100, 50),
                    ["C"] = new("Depth", 0, 100, 50),
                    ["D"] = new("Init Phase", 0, 12, 6),
                    ["E"] = new("Step Rate", 0, 115, 0),
                },
                ["AA_MANUAL_PAN"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Position", 0, 100, 50),
                },
                ["AA_MANUAL_PAN_SEQ"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Sw", 0, 1, 0),
                    ["B"] = new("Sync", 0, 1, 0),
                    ["C"] = new("Retrig", 0, 1, 0),
                    ["D"] = new("Target", 0, 0, 0),
                    ["E"] = new("Seq Rate", 0, 114, 0),
                    ["F"] = new("Seq Max", 0, 15, 8),
                    ["G"] = new("Seq Val 1", 0, 100, 50),
                    ["H"] = new("Seq Val 2", 0, 100, 50),
                    ["I"] = new("Seq Val 3", 0, 100, 50),
                    ["J"] = new("Seq Val 4", 0, 100, 50),
                    ["K"] = new("Seq Val 5", 0, 100, 50),
                    ["L"] = new("Seq Val 6", 0, 100, 50),
                    ["M"] = new("Seq Val 7", 0, 100, 50),
                    ["N"] = new("Seq Val 8", 0, 100, 50),
                    ["O"] = new("Seq Val 9", 0, 100, 50),
                    ["P"] = new("Seq Val 10", 0, 100, 50),
                    ["Q"] = new("Seq Val 11", 0, 100, 50),
                    ["R"] = new("Seq Val 12", 0, 100, 50),
                    ["S"] = new("Seq Val 13", 0, 100, 50),
                    ["T"] = new("Seq Val 14", 0, 100, 50),
                    ["U"] = new("Seq Val 15", 0, 100, 50),
                    ["V"] = new("Seq Val 16", 0, 100, 50),
                },
                ["AA_STEREO_ENHANCE"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Low Cut", 0, 29, 14),
                    ["B"] = new("High Cut", 0, 29, 14),
                    ["C"] = new("Enhance", 0, 100, 50),
                },
                ["AA_TREMOLO"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Rate", 0, 115, 0),
                    ["B"] = new("Depth", 0, 100, 50),
                    ["C"] = new("Wave Form", 0, 100, 50),
                    ["D"] = new("Level", 0, 100, 50),
                },
                ["AA_TREMOLO_SEQ"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Sw", 0, 1, 0),
                    ["B"] = new("Sync", 0, 1, 0),
                    ["C"] = new("Retrig", 0, 1, 0),
                    ["D"] = new("Target", 0, 1, 0),
                    ["E"] = new("Seq Rate", 0, 114, 0),
                    ["F"] = new("Seq Max", 0, 15, 8),
                    ["G"] = new("Seq Val 1", 0, 100, 50),
                    ["H"] = new("Seq Val 2", 0, 100, 50),
                    ["I"] = new("Seq Val 3", 0, 100, 50),
                    ["J"] = new("Seq Val 4", 0, 100, 50),
                    ["K"] = new("Seq Val 5", 0, 100, 50),
                    ["L"] = new("Seq Val 6", 0, 100, 50),
                    ["M"] = new("Seq Val 7", 0, 100, 50),
                    ["N"] = new("Seq Val 8", 0, 100, 50),
                    ["O"] = new("Seq Val 9", 0, 100, 50),
                    ["P"] = new("Seq Val 10", 0, 100, 50),
                    ["Q"] = new("Seq Val 11", 0, 100, 50),
                    ["R"] = new("Seq Val 12", 0, 100, 50),
                    ["S"] = new("Seq Val 13", 0, 100, 50),
                    ["T"] = new("Seq Val 14", 0, 100, 50),
                    ["U"] = new("Seq Val 15", 0, 100, 50),
                    ["V"] = new("Seq Val 16", 0, 100, 50),
                },
                ["AA_VIBRATO"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Rate", 0, 114, 0),
                    ["B"] = new("Depth", 0, 100, 50),
                    ["C"] = new("Color", 0, 100, 50),
                    ["D"] = new("D.Level", 0, 100, 50),
                    ["E"] = new("E.Level", 0, 100, 50),
                },
                ["AA_VIBRATO_SEQ"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Sw", 0, 1, 0),
                    ["B"] = new("Sync", 0, 1, 0),
                    ["C"] = new("Retrig", 0, 1, 0),
                    ["D"] = new("Target", 0, 2, 1),
                    ["E"] = new("Seq Rate", 0, 114, 0),
                    ["F"] = new("Seq Max", 0, 15, 8),
                    ["G"] = new("Seq Val 1", 0, 100, 50),
                    ["H"] = new("Seq Val 2", 0, 100, 50),
                    ["I"] = new("Seq Val 3", 0, 100, 50),
                    ["J"] = new("Seq Val 4", 0, 100, 50),
                    ["K"] = new("Seq Val 5", 0, 100, 50),
                    ["L"] = new("Seq Val 6", 0, 100, 50),
                    ["M"] = new("Seq Val 7", 0, 100, 50),
                    ["N"] = new("Seq Val 8", 0, 100, 50),
                    ["O"] = new("Seq Val 9", 0, 100, 50),
                    ["P"] = new("Seq Val 10", 0, 100, 50),
                    ["Q"] = new("Seq Val 11", 0, 100, 50),
                    ["R"] = new("Seq Val 12", 0, 100, 50),
                    ["S"] = new("Seq Val 13", 0, 100, 50),
                    ["T"] = new("Seq Val 14", 0, 100, 50),
                    ["U"] = new("Seq Val 15", 0, 100, 50),
                    ["V"] = new("Seq Val 16", 0, 100, 50),
                },
                ["AA_PATTERN_SLICER"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Rate", 0, 114, 0),
                    ["B"] = new("Duty", 0, 98, 49),
                    ["C"] = new("Attack", 0, 100, 50),
                    ["D"] = new("Pattern", 0, 20, 10),
                    ["E"] = new("Depth", 0, 100, 50),
                    ["F"] = new("Threshold", 0, 30, 15),
                    ["G"] = new("Gain", 0, 20, 10),
                },
                ["AA_STEP_SLICER"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Rate", 0, 114, 0),
                    ["B"] = new("Step Max", 0, 15, 8),
                    ["C"] = new("Step Len1", 0, 100, 50),
                    ["D"] = new("Step Len2", 0, 100, 50),
                    ["E"] = new("Step Len3", 0, 100, 50),
                    ["F"] = new("Step Len4", 0, 100, 50),
                    ["G"] = new("Step Len5", 0, 100, 50),
                    ["H"] = new("Step Len6", 0, 100, 50),
                    ["I"] = new("Step Len7", 0, 100, 50),
                    ["J"] = new("Step Len8", 0, 100, 50),
                    ["K"] = new("Step Len9", 0, 100, 50),
                    ["L"] = new("Step Len10", 0, 100, 50),
                    ["M"] = new("Step Len11", 0, 100, 50),
                    ["N"] = new("Step Len12", 0, 100, 50),
                    ["O"] = new("Step Len13", 0, 100, 50),
                    ["P"] = new("Step Len14", 0, 100, 50),
                    ["Q"] = new("Step Len15", 0, 100, 50),
                    ["R"] = new("Step Len16", 0, 100, 50),
                    ["S"] = new("Step LvL1", 0, 100, 50),
                    ["T"] = new("Step LvL2", 0, 100, 50),
                    ["U"] = new("Step LvL3", 0, 100, 50),
                    ["V"] = new("Step LvL4", 0, 100, 50),
                    ["W"] = new("Step LvL5", 0, 100, 50),
                    ["X"] = new("Step LvL6", 0, 100, 50),
                    ["Y"] = new("Step LvL7", 0, 100, 50),
                    ["Z"] = new("Step LvL8", 0, 100, 50),
                    ["0"] = new("Step LvL9", 0, 100, 50),
                    ["1"] = new("Step LvL10", 0, 100, 50),
                    ["2"] = new("Step LvL11", 0, 100, 50),
                    ["3"] = new("Step LvL12", 0, 100, 50),
                    ["4"] = new("Step LvL13", 0, 100, 50),
                    ["5"] = new("Step LvL14", 0, 100, 50),
                    ["6"] = new("Step LvL15", 0, 100, 50),
                    ["7"] = new("Step LvL16", 0, 100, 50),
                    ["8"] = new("Depth", 0, 100, 50),
                    ["9"] = new("Threshold", 0, 30, 15),
                    ["#"] = new("Gain", 0, 20, 10),
                },
                ["AA_DELAY"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Time", 0, 2011, 0),
                    ["B"] = new("Feedback", 0, 100, 50),
                    ["C"] = new("D.Level", 0, 100, 50),
                    ["D"] = new("Low Cut", 0, 20, 10),
                    ["E"] = new("High Cut", 0, 29, 14),
                    ["F"] = new("E.Level", 0, 120, 60),
                },
                ["AA_PANNING_DELAY"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Time", 0, 2011, 0),
                    ["B"] = new("Feedback", 0, 100, 50),
                    ["C"] = new("D.Level", 0, 100, 50),
                    ["D"] = new("Low Cut", 0, 20, 10),
                    ["E"] = new("High Cut", 0, 29, 14),
                    ["F"] = new("E.Level", 0, 120, 60),
                },
                ["AA_REVERSE_DELAY"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Time", 0, 2011, 0),
                    ["B"] = new("Feedback", 0, 100, 50),
                    ["C"] = new("D.Level", 0, 100, 50),
                    ["D"] = new("Low Cut", 0, 20, 10),
                    ["E"] = new("High Cut", 0, 29, 14),
                    ["F"] = new("E.Level", 0, 120, 60),
                },
                ["AA_MOD_DELAY"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Time", 0, 2011, 0),
                    ["B"] = new("Feedback", 0, 100, 50),
                    ["C"] = new("Mod Depth", 0, 100, 50),
                    ["D"] = new("D.Level", 0, 100, 50),
                    ["E"] = new("Low Cut", 0, 20, 10),
                    ["F"] = new("High Cut", 0, 29, 14),
                    ["G"] = new("E.Level", 0, 120, 60),
                },
                ["AA_TAPE_ECHO"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Time", 0, 2011, 0),
                    ["B"] = new("Feedback", 0, 100, 50),
                    ["C"] = new("D.Level", 0, 100, 50),
                    ["D"] = new("Low Cut", 0, 20, 10),
                    ["E"] = new("High Cut", 0, 29, 14),
                    ["F"] = new("E.Level", 0, 120, 60),
                },
                ["AA_TAPE_ECHO_V505V2"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Repeat Rate", 0, 100, 0),
                    ["B"] = new("Intensity", 0, 100, 50),
                    ["C"] = new("D.Level", 0, 100, 50),
                    ["D"] = new("Bass", 0, 100, 50),
                    ["E"] = new("Treble", 0, 100, 50),
                    ["F"] = new("E.Level", 0, 120, 60),
                },
                ["AA_GRANULAR_DELAY"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Time", 0, 100, 0),
                    ["B"] = new("Feedback", 0, 100, 50),
                    ["C"] = new("E.Level", 0, 100, 50),
                },
                ["AA_WARP"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Level", 0, 100, 50),
                },
                ["AA_TWIST"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Release", 0, 1, 0),
                    ["B"] = new("Rise", 0, 100, 50),
                    ["C"] = new("Fall", 0, 100, 50),
                    ["D"] = new("Level", 0, 100, 50),
                },
                ["AA_ROLL"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Time", 0, 1011, 0),
                    ["B"] = new("Repeat", 1, 100, 50),
                    ["C"] = new("Roll", 0, 4, 2),
                    ["D"] = new("Balance", 0, 100, 50),
                },
                ["AA_ROLL_V505V2"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Time", 0, 1011, 0),
                    ["B"] = new("Feedback", 0, 100, 50),
                    ["C"] = new("Roll", 0, 4, 2),
                    ["D"] = new("Balance", 0, 100, 50),
                },
                ["AA_FREEZE"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Attack", 0, 100, 50),
                    ["B"] = new("Release", 0, 100, 50),
                    ["C"] = new("Decay", 0, 100, 50),
                    ["D"] = new("Sustain", 0, 100, 50),
                    ["E"] = new("Balance", 0, 100, 50),
                },
                ["AA_CHORUS"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Rate", 0, 114, 0),
                    ["B"] = new("Depth", 0, 100, 50),
                    ["C"] = new("Low Cut", 0, 29, 14),
                    ["D"] = new("High Cut", 0, 29, 14),
                    ["E"] = new("D.Level", 0, 100, 50),
                    ["F"] = new("E.Level", 0, 100, 50),
                },
                ["AA_REVERB"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Time", 0, 100, 0),
                    ["B"] = new("Pre Delay", 0, 500, 0),
                    ["C"] = new("Density", 0, 9, 5),
                    ["D"] = new("Low Cut", 0, 29, 14),
                    ["E"] = new("High Cut", 0, 29, 14),
                    ["F"] = new("D.Level ", 0, 100, 50),
                    ["G"] = new("E.Level", 0, 100, 50),
                },
                ["AA_GATE_REVERB"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Time", 0, 100, 0),
                    ["B"] = new("Pre Delay", 0, 500, 0),
                    ["C"] = new("Threshold", 0, 100, 50),
                    ["D"] = new("Low Cut", 0, 29, 14),
                    ["E"] = new("High Cut", 0, 29, 14),
                    ["F"] = new("D.Level ", 0, 100, 50),
                    ["G"] = new("E.Level", 0, 100, 50),
                },
                ["AA_REVERSE_REVERB"] = new Dictionary<string, ParamMeta>
                {
                    ["A"] = new("Time", 0, 10, 0),
                    ["B"] = new("Pre Delay", 0, 500, 0),
                    ["C"] = new("Gate Time", 0, 10, 5),
                    ["D"] = new("Low Cut", 0, 29, 14),
                    ["E"] = new("High Cut", 0, 29, 14),
                    ["F"] = new("D.Level ", 0, 100, 50),
                    ["G"] = new("E.Level", 0, 100, 50),
                },
            };

        public static ParamMeta GetParamMeta(string effectKey, string paramKey)
            => Map.TryGetValue(effectKey, out var dict) && dict.TryGetValue(paramKey, out var meta)
                ? meta
                : new ParamMeta(paramKey, 0, 127, 0);

        public static IEnumerable<string> EffectKeys() => Map.Keys;
        public static IEnumerable<KeyValuePair<string, ParamMeta>> Params(string effectKey)
            => Map.TryGetValue(effectKey, out var dict) ? dict : Array.Empty<KeyValuePair<string, ParamMeta>>();
    }
}
